### ISSUE TITLE
[Suggestion] Disable Startup Sha256 Calculations And Make Them Only When Is Necessary

### ISSUE THREAD

**Issue by Seikikai** [civitai/sd_civitai_extension#105]
It Will Be Good If Sha256 Calculations Be Disabled At The Startup Of The Program And Be Done Only When The Checkpoint/Lora/Hypernetwork/Etc Be Used (Load/See Info/Used In A Prompt) To Prevent That People With Lot Of Embedings Have To Wait Long Times Until They Can Start Using SD.

**Comment by TsengSR** [comment]
I second that. The scan time is hilarious! It is scanning the same models over and over again. 

It should keep a record of scanned files and remember their hash and not re-scan it unless the file's timestamp changes. I have a lot of models and Loras, around 800-1000 GB in total and hence stored on a slower drive (at least most of the less frequently used checkpoints). The frequent checkpoints I have on M.2 SSDs which is fine, but for Loras a slow HDD or network drive is fine. It takes 30 to 60 minutes and slows down my whole network because every time I restart it it scans everything

**Comment by JustMaier** [comment]
> I second that. The scan time is hilarious! It is scanning the same models over and over again.

It shouldn't be doing this. It does store the hashes of all assets in the same cache as the model SHA256 hashes. If you're seeing full rescans on every boot, there may be something wrong with your SD Web UI instance.
