### ISSUE TITLE
[Feature Request] add a button to reconnect to civitai.

### ISSUE THREAD

**Issue by fcolecumberri** [civitai/sd_civitai_extension#117]
Sometimes when the system is idle the connection just get lost (in many ways, it's normal) and the next message appear:

```
Civitai Link: Disconnected from Civitai Link Server
```

I can understand that this may be because of timeouts or other type of control (at the end of the day this is like creating and inverse server over nat tpc, the challenges are there). However the only way to reconnect is to shutdown a1111 and start it again. It would be nice to just add a button to try to connect again.

**Comment by jiveabillion** [comment]
I have done this by adding an additional icon to the top right (it looks like a heart) that shows the status of the link. You can click on that icon to reconnect the link when it becomes disconnected. I use it often because SDXL renders often cause the link to disconnect. I have created a PR with this repository, but if you want to try it out now, you can pull the code from https://github.com/jiveabillion/sd_civitai_extension
![image](https://github.com/civitai/sd_civitai_extension/assets/1770184/35169b28-2235-4e24-bfe4-c2e9621ed146)

**Comment by getsmartt** [comment]
> I have done this by adding an additional icon to the top right (it looks like a heart) that shows the status of the link. You can click on that icon to reconnect the link when it becomes disconnected. I use it often because SDXL renders often cause the link to disconnect. I have created a PR with this repository, but if you want to try it out now, you can pull the code from https://github.com/jiveabillion/sd_civitai_extension

@jiveabillion 
wanted to try out your repository, but getting this error...
` ImportError: cannot import name 'get_link_status' from  @'scripts.link'`

any ideas?
Thanks.

**Comment by jiveabillion** [comment]
Sorry for taking so long to get to this, I've had a lot going on in my life recently. I updated my fork so it should work now

**Comment by fcolecumberri** [comment]
I haven't tested, however I guess as https://github.com/civitai/sd_civitai_extension/pull/122 got merged, this should be closed.
