### ISSUE TITLE
Installed via Extensions Tab, but no tab appeared. 

### ISSUE THREAD

**Issue by Artyrm** [civitai/sd_civitai_extension#24]
I'm on Windows.
Other extensions (ex. Image browser) work just fine.

Console says:

```
Civitai: Check resources for missing preview images
Civitai: Found 1 resources missing preview images
Civitai: No preview images found on Civitai
```

Maybe that's the case?

```
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Civitai Link revision: 579d6940168230daf0d32a1c936c0dd0ba27b433
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Civitai Link requirements...
[+] python-socketio[client] version 5.7.2 installed.
```

UPD Deleted/reinstalled/restarted Automatic several times, but no joy.

**Comment by Artyrm** [comment]
No I noticed some CivitAi icon in top right corner of WebUI, with red dot near it. Not sure what does it mean.

**Comment by akinLiu** [comment]
The same issue

**Comment by medledan** [comment]
I have the same issue.  Commit version 579d694

**Comment by x-ili-x** [comment]
It's not usable yet unfortunately. They changed direction mid development. For some reason I stil like seeing it boot up though, lol. It also created preview images of all my checkpoints which is cool.

**Comment by JustMaier** [comment]
There isn't an extension tab, just a settings tab. The bulk of the features provided by the extension at this time are either automatic (like grabbing preview images and models based on the model hash) or are in preview and only available to Supporters (Civitai Link).

We may have a tab in the UI at some point, but it's not currently on our roadmap for this extension. Rather than maintaining two UIs that allow you to browse models in the repo, we've instead opted to just make it easy to load things into SD while you browse the site.

**Comment by Artyrm** [comment]
Alright, guess I didn't get it from readme. So once an extension that allows to browse Civitai via tab, and decided to google it.
Thank you for pointing out.
I'll close it then.
